## service definition
version:"3.3"
services:
  webserver:
    image:ubuntu
    ports:
      -"80:80"
    networks:
      -webnet

  redis:
    image: redis
    networks:
      -webnet

## Network Definition
networks:
  webnet:

## Data Volume Definition
Volume:
  data-volume:

## Container
links:
	- logserver
	- logserver:log01

## Ports
ports:
	- "3000"
	- "8000:80"
	- "127.0.0.1:8000:8000"


## exposes
expose:
	- "3000"
