services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:latest
    restart: always
    ports:
      - "3000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-local:/app/backend/data

  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - open-local:/root/.ollama
    

volumes:
  open-webui-local:
    external: true
  open-local:
    external: true
