# Base Images
FROM ubuntu:latest

# RUN Command
RUN echo Hello~ It's Shell Type command.
RUN ["echo", "Hello~ It's Exec Type Command."]
RUN ["/bin/bash", "-c", "echo 'Hello~ It's /bin/bash execution in Shell Type Command.'"]
