
apiVersion: v1
kind: Service
metadata:
  name: remoteapi
  labels:
    run: remoteapi
spec:
  type: NodePort
  ports:
    - nodePort : 30800   # outter port
      port: 8080         # service port
      targetPort: 8000     # container port (pod port)
      protocol: TCP
      name: http
  selector:
    app: remoteapi
  type: LoadBalancer
  externalIPs:
    - 13.209.180.129
